apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mzidek-tenant/devfile-sample-python-basic/devfile-sample-python-basic@sha256:4c3e6fb486c9809abcd8fa0cde55a05587bc5b8c77223afd08ca363559718a09
        name: my-python
        resources: {}
status: {}
