apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: my-devfile-sample-python-basic-gufa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mzidek-tenant/devfile-sample-python-basic/my-devfile-sample-python-basic-gufa@sha256:2405fa4dcaa99f46c06b108b949c89a621f7f84f0dd26ebe831a379e2d35b952
        name: my-python
        resources: {}
status: {}
