apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-devfile-sample-python-basic-gufa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-devfile-sample-python-basic-gufa
    app.kubernetes.io/part-of: devfile-sample-python-basic
  name: my-devfile-sample-python-basic-gufa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: my-devfile-sample-python-basic-gufa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: my-devfile-sample-python-basic-gufa
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mzidek-tenant/devfile-sample-python-basic/my-devfile-sample-python-basic-gufa@sha256:c501a071c81a7a00d79fd665c73e92e75fedf8edebe8d4fc3e8c583511b60c27
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
