apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-devfile-sample-python-basic-gufa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-devfile-sample-python-basic-gufa
    app.kubernetes.io/part-of: devfile-sample-python-basic
  name: my-devfile-sample-python-basic-gufa
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: my-devfile-sample-python-basic-gufa
status:
  loadBalancer: {}
